spring:
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /blog/v1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zoe.blog.model
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com  # oss对外服务的访问域名
    accessKeyId: accessKeyId # 访问身份验证中用到用户标识
    accessKeySecret: accessKeySecret # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: zoe-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://127.0.0.1:8080/blog/v1/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: blog/images/ # 上传文件夹路径前缀

jwt:
  tokenHeader: Authorization
  secret: 2020blog07lxl18
  tokenHead: 'Bearer '
  expiration: 86400000 # 1000 * 60 * 60 * 24(一天）
#  expiration: 60000 # 1000 * 60 * 5
# 每日定时生成uv当天的数据库字段：零点生成
time:
  cron: 1 0 0 * * ?

logging:
  level:
    com.zoe.blog.dao: debug

